name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
# assignees:
#   - prometheas
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!  You may upload images and/or screen recordings to augment written description.
      value: |
        ## What I Did
        
        Please describe what you did / were trying to do when you ran into the trouble...
        
        ## What I Expected to Happen
        
        Please describe the outcome you anticipated...
        
        ## What Actually Happened
        
        Please describe the problematic outcome(s)...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Brave
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
    validations:
      required: true
  - type: dropdown
    id: distribution-channel
    attributes:
      label: Distribution Channel
      description: How did you install your extension build?
      options:
        - Apple App Store
        - Google Play Store
        - Other Store
        - Built locally from source
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
