name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - prometheas
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.  Please use this to report matters that are unexpected / error situations you encounter using the extension.  If the problem you're describing is instead a shortcoming of the extension (a "missing" capability), please submit a feature request instead.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-i-did
    attributes:
      label: What I Did...
      description: |
        Please describe what you did / were trying to do when you ran into the trouble...
    validations:
      required: true
  - type: textarea
    id: what-i-expected
    attributes:
      label: What I'd Expected to Happen...
      description: |
        Please describe the outcome you'd anticipated...
    validations:
      required: true
  - type: textarea
    id: what-actually-happened
    attributes:
      label: What Actually Happened...
      description: |
        Please describe the problematic outcome(s) you'd experienced instead...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Brave
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
    validations:
      required: true
  - type: dropdown
    id: distribution-channel
    attributes:
      label: Distribution Channel
      description: How did you install your extension build?
      options:
        - Apple App Store
        - Google Play Store
        - Other Store
        - Built locally from source
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
